### PR TITLE
Fix/let mission drawer locked

### LINKED ISSUE #34: 任務頁面上再點功能說明，功能說明頁面下面不會有不透明層遮罩
## **Describe the bug**
任務頁面上再點功能說明，功能說明頁面不會有不透明層遮罩 。功能說明頁面上的字會變成直接疊在前一個頁面，沒有下面一個不透明層，字會看不清楚。

## **Steps To Reproduce**
1. 主畫面說隨便按一個已經存在的任務
2. 在任務頁面再按右上角漢堡選單裡的「功能介紹」
3. 會出現如標題的畫面

## **Expected behavior**
「功能說明」的頁面下應該要立刻從任務頁面回到地圖主畫面。而且「功能說明」下應該要有灰色的不透明層。而不是直接蓋在前一個畫面。

## **Screenshots**
IMG_3170

## **Smartphone (please complete the following information):**
 - Device: iPhone 8
 - OS: 14.4
 - Browser: chrome
 - Version: 87.0.4280.77

### PR DESCRIPTION
**Pull request by jiangxin1998**
Fixes #34 
## Why do we need this PR?
 * When people add mission ,they can't use menu and filter

## How did you address the issue?
 * We locked menu and filter when they are adding mission

### CODE REVIEW

File: src/pages/MapPage/components/Filter/FilterDrawer.js [hunk 1]
```diff
@@ -96,7 +101,6 @@ const FilterDrawer = props => {
   return (
     <Drawer
       anchor={isWidthUp('sm', width) ? 'left' : 'bottom'}
-      variant='persistent'
       open={open}
       onClose={onClose}
```
Comment (KalleChen) [inline src/pages/MapPage/components/Filter/FilterDrawer.js:105]: Please change onClose here to handleCloseFilter

Comment (jiangxin1998) [reply src/pages/MapPage/components/Filter/FilterDrawer.js]: Already change

**Review by KalleChen — APPROVED** [review]
